# Generated by Django 3.1.6 on 2021-02-14 19:44

from django.db import migrations, models
import products.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=2)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to=products.models.upload_image_product)),
            ],
        ),
    ]
